{% set name = "capsula" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/capsula-{{ version }}.tar.gz
  sha256: ee5132d13f6739599825d4b0ffefc5684f449efe5ff4fd857ce54599777d54dd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - poetry-core
    - pip
  run:
    - python >=3.8
    - py-cpuinfo >=9.0.0
    - gitpython >=3.1.31
    - tomli >=2.0.1
    - typing-extensions >=4.7.1
    - orjson >=3.9.10
    - typer >=0.9.0

test:
  imports:
    - capsula
  commands:
    - pip check
  requires:
    - pip
    - git

about:
  home: https://github.com/shunichironomura/capsula
  summary: A Python package to capture function execution contexts
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - shunichironomura
