{% set name = "capsula" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/capsula-{{ version }}.tar.gz
  sha256: 429139406a60ae0d7d114066945b7612db623881aca621a87b7f29a1e3c63f9e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - poetry-core
    - pip
  run:
    - python >=3.8
    - py-cpuinfo >=9.0.0
    - gitpython >=3.1.31
    - tomli >=2.0.1
    - typing-extensions >=4.7.1
    - orjson >=3.9.10
    - typer >=0.9.0

test:
  imports:
    - capsula
  commands:
    - pip check
  requires:
    - pip
    - git

about:
  home: https://github.com/shunichironomura/capsula
  summary: A Python package to capture function execution contexts
  license: MIT AND PSF-2.0
  license_file: LICENSE
  doc_url: https://shunichironomura.github.io/capsula/
  dev_url: https://github.com/shunichironomura/capsula
  doc_source_url: https://github.com/shunichironomura/capsula/blob/main/README.md

extra:
  recipe-maintainers:
    - shunichironomura
