{% set name = "capsula" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/capsula-{{ version }}.tar.gz
  sha256: 75c1cf245e40d484cb341315e0e3a1bea22264b4deec61212da55c7d411fdbf4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - poetry-core
    - pip
  run:
    - python >=3.8
    - click >=8.1.3
    - pydantic >=2.0.2
    - py-cpuinfo >=9.0.0
    - gitpython >=3.1.31
    - tomli >=2.0.1
    - typing-extensions >=4.7.1
    - orjson >=3.9.10
    - typer >= 0.9.0
    - rich >= 13.7.0
    - eval-type-backport >= 0.1.3 # This is not available on conda-forge

test:
  imports:
    - capsula
  commands:
    - pip check
  requires:
    - pip
    - git

about:
  home: https://github.com/shunichironomura/capsula
  summary: A Python package to capture function execution contexts
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - shunichironomura
